# This file is auto-generated. DO NOT MODIFY!

GCC_SAFE_FILES :=    \
    $(BUILD_DIR)/src/asset_loading.o    \
    $(BUILD_DIR)/src/audio.o    \
    $(BUILD_DIR)/src/audiomgr.o    \
    $(BUILD_DIR)/src/borders.o    \
    $(BUILD_DIR)/src/camera.o    \
    $(BUILD_DIR)/src/controller.o    \
    $(BUILD_DIR)/src/font.o    \
    $(BUILD_DIR)/src/game.o    \
    $(BUILD_DIR)/src/game_text.o    \
    $(BUILD_DIR)/src/gzip.o    \
    $(BUILD_DIR)/src/main.o    \
    $(BUILD_DIR)/src/memory.o    \
    $(BUILD_DIR)/src/thread0_epc.o    \
    $(BUILD_DIR)/src/thread30_track_loading.o    \
    $(BUILD_DIR)/src/thread3_main.o    \
    $(BUILD_DIR)/src/vehicle_bluey.o    \
    $(BUILD_DIR)/src/vehicle_bubbler.o    \
    $(BUILD_DIR)/src/vehicle_rocket.o    \
    $(BUILD_DIR)/src/vehicle_smokey.o    \
    $(BUILD_DIR)/src/vehicle_wizpig.o    \
    $(BUILD_DIR)/src/video.o    \
    $(BUILD_DIR)/src/usb/dkr_usb.o    \
    $(BUILD_DIR)/src/usb/reset.o    \
    $(BUILD_DIR)/src/usb/usb.o    \
    $(BUILD_DIR)/lib/src/al/alBnkfNew.o    \
    $(BUILD_DIR)/lib/src/al/alCopy.o    \
    $(BUILD_DIR)/lib/src/al/alCSPGetChlVol.o    \
    $(BUILD_DIR)/lib/src/al/alCSPGetState.o    \
    $(BUILD_DIR)/lib/src/al/alCSPGetTempo.o    \
    $(BUILD_DIR)/lib/src/al/alCSPSetBank.o    \
    $(BUILD_DIR)/lib/src/al/alCSPSetChlPan.o    \
    $(BUILD_DIR)/lib/src/al/alCSPSetChlVol.o    \
    $(BUILD_DIR)/lib/src/al/alCSPSetSeq.o    \
    $(BUILD_DIR)/lib/src/al/alCSPSetTempo.o    \
    $(BUILD_DIR)/lib/src/al/alCSPSetVol.o    \
    $(BUILD_DIR)/lib/src/al/alHeapDBAlloc.o    \
    $(BUILD_DIR)/lib/src/al/alHeapInit.o    \
    $(BUILD_DIR)/lib/src/al/alSeqpGetChlFXMix.o    \
    $(BUILD_DIR)/lib/src/al/alSynDelete.o    \
    $(BUILD_DIR)/lib/src/al/alSynSetFXMix.o    \
    $(BUILD_DIR)/lib/src/al/alSynSetPitch.o    \
    $(BUILD_DIR)/lib/src/al/alSynSetPriority.o    \
    $(BUILD_DIR)/lib/src/al/alSynSetVol.o    \
    $(BUILD_DIR)/lib/src/al/alSynStartVoice.o    \
    $(BUILD_DIR)/lib/src/al/alSynStopVoice.o    \
    $(BUILD_DIR)/lib/src/al/cents2ratio.o    \
    $(BUILD_DIR)/lib/src/al/cseq.o    \
    $(BUILD_DIR)/lib/src/al/cspplay.o    \
    $(BUILD_DIR)/lib/src/al/cspstop.o    \
    $(BUILD_DIR)/lib/src/al/env.o    \
    $(BUILD_DIR)/lib/src/al/event.o    \
    $(BUILD_DIR)/lib/src/al/filter.o    \
    $(BUILD_DIR)/lib/src/al/load.o    \
    $(BUILD_DIR)/lib/src/al/mainbus.o    \
    $(BUILD_DIR)/lib/src/al/resample.o    \
    $(BUILD_DIR)/lib/src/al/save.o    \
    $(BUILD_DIR)/lib/src/al/sl.o    \
    $(BUILD_DIR)/lib/src/al/synaddplayer.o    \
    $(BUILD_DIR)/lib/src/al/synallocvoice.o    \
    $(BUILD_DIR)/lib/src/al/synfreevoice.o    \
    $(BUILD_DIR)/lib/src/gu/cosf.o    \
    $(BUILD_DIR)/lib/src/gu/guMtxUtil.o    \
    $(BUILD_DIR)/lib/src/gu/guPerspectiveF.o    \
    $(BUILD_DIR)/lib/src/gu/sinf.o    \
    $(BUILD_DIR)/lib/src/libc/ldiv.o    \
    $(BUILD_DIR)/lib/src/libc/rmonPrintf.o    \
    $(BUILD_DIR)/lib/src/libc/string.o    \
    $(BUILD_DIR)/lib/src/libc/xlitob.o    \
    $(BUILD_DIR)/lib/src/libc/xprintf.o    \
    $(BUILD_DIR)/lib/src/mips1/al/alAuxBusPull.o    \
    $(BUILD_DIR)/lib/src/mips1/al/alFxNew.o    \
    $(BUILD_DIR)/lib/src/mips1/al/alSynAllocFX.o    \
    $(BUILD_DIR)/lib/src/mips1/al/alSynSetPan.o    \
    $(BUILD_DIR)/lib/src/mips1/al/alSynStartVoiceParams.o    \
    $(BUILD_DIR)/lib/src/mips1/al/reverb.o    \
    $(BUILD_DIR)/lib/src/mips1/al/seqplayer.o    \
    $(BUILD_DIR)/lib/src/mips1/al/synthesizer.o    \
    $(BUILD_DIR)/lib/src/mips1/al/unknown_0646F0.o    \
    $(BUILD_DIR)/lib/src/mips1/al/unknown_0647A0.o    \
    $(BUILD_DIR)/lib/src/mips1/al/unknown_064800.o    \
    $(BUILD_DIR)/lib/src/mips1/os/osCreatePiManager.o    \
    $(BUILD_DIR)/lib/src/mips1/sc/sched.o    \
    $(BUILD_DIR)/lib/src/os/contpfs.o    \
    $(BUILD_DIR)/lib/src/os/contramread.o    \
    $(BUILD_DIR)/lib/src/os/contramwrite.o    \
    $(BUILD_DIR)/lib/src/os/contreaddata.o    \
    $(BUILD_DIR)/lib/src/os/controller.o    \
    $(BUILD_DIR)/lib/src/os/crc.o    \
    $(BUILD_DIR)/lib/src/os/devmgr.o    \
    $(BUILD_DIR)/lib/src/os/dp.o    \
    $(BUILD_DIR)/lib/src/os/osAiSetFrequency.o    \
    $(BUILD_DIR)/lib/src/os/osAiSetNextBuffer.o    \
    $(BUILD_DIR)/lib/src/os/osCreateMesgQueue.o    \
    $(BUILD_DIR)/lib/src/os/osCreateThread.o    \
    $(BUILD_DIR)/lib/src/os/osDestroyThread.o    \
    $(BUILD_DIR)/lib/src/os/osDpGetStatus.o    \
    $(BUILD_DIR)/lib/src/os/osDpSetNextBuffer.o    \
    $(BUILD_DIR)/lib/src/os/osDpSetStatus.o    \
    $(BUILD_DIR)/lib/src/os/osEepromProbe.o    \
    $(BUILD_DIR)/lib/src/os/osEepromRead.o    \
    $(BUILD_DIR)/lib/src/os/osEepromWrite.o    \
    $(BUILD_DIR)/lib/src/os/osEpiRawStartDma.o    \
    $(BUILD_DIR)/lib/src/os/osEPiRawWriteIo.o    \
    $(BUILD_DIR)/lib/src/os/osGetActiveQueue.o    \
    $(BUILD_DIR)/lib/src/os/osGetThreadPri.o    \
    $(BUILD_DIR)/lib/src/os/osGetTime.o    \
    $(BUILD_DIR)/lib/src/os/osInitialize.o    \
    $(BUILD_DIR)/lib/src/os/osJamMesg.o    \
    $(BUILD_DIR)/lib/src/os/osMotor.o    \
    $(BUILD_DIR)/lib/src/os/osPfsChecker.o    \
    $(BUILD_DIR)/lib/src/os/osPfsDeleteFile.o    \
    $(BUILD_DIR)/lib/src/os/osPfsFileState.o    \
    $(BUILD_DIR)/lib/src/os/osPfsFindFile.o    \
    $(BUILD_DIR)/lib/src/os/osPfsFreeBlocks.o    \
    $(BUILD_DIR)/lib/src/os/osPfsInit.o    \
    $(BUILD_DIR)/lib/src/os/osPfsIsPlug.o    \
    $(BUILD_DIR)/lib/src/os/osPfsNumFiles.o    \
    $(BUILD_DIR)/lib/src/os/osPfsReFormat.o    \
    $(BUILD_DIR)/lib/src/os/osPiGetCmdQueue.o    \
    $(BUILD_DIR)/lib/src/os/osPiRawReadIo.o    \
    $(BUILD_DIR)/lib/src/os/osPiRawStartDma.o    \
    $(BUILD_DIR)/lib/src/os/osPiStartDma.o    \
    $(BUILD_DIR)/lib/src/os/osRecvMesg.o    \
    $(BUILD_DIR)/lib/src/os/osSendMesg.o    \
    $(BUILD_DIR)/lib/src/os/osSetEventMesg.o    \
    $(BUILD_DIR)/lib/src/os/osSetThreadPri.o    \
    $(BUILD_DIR)/lib/src/os/osSetTime.o    \
    $(BUILD_DIR)/lib/src/os/osSetTimer.o    \
    $(BUILD_DIR)/lib/src/os/osSpTaskYield.o    \
    $(BUILD_DIR)/lib/src/os/osSpTaskYielded.o    \
    $(BUILD_DIR)/lib/src/os/osStartThread.o    \
    $(BUILD_DIR)/lib/src/os/osStopThread.o    \
    $(BUILD_DIR)/lib/src/os/osTimer.o    \
    $(BUILD_DIR)/lib/src/os/osViBlack.o    \
    $(BUILD_DIR)/lib/src/os/osViGetCurrentFramebuffer.o    \
    $(BUILD_DIR)/lib/src/os/osViGetNextFramebuffer.o    \
    $(BUILD_DIR)/lib/src/os/osViMgr.o    \
    $(BUILD_DIR)/lib/src/os/osVirtualToPhysical.o    \
    $(BUILD_DIR)/lib/src/os/osViSetEvent.o    \
    $(BUILD_DIR)/lib/src/os/osViSetMode.o    \
    $(BUILD_DIR)/lib/src/os/osViSetSpecialFeatures.o    \
    $(BUILD_DIR)/lib/src/os/osViSwapBuffer.o    \
    $(BUILD_DIR)/lib/src/os/osYieldThread.o    \
    $(BUILD_DIR)/lib/src/os/pfsallocatefile.o    \
    $(BUILD_DIR)/lib/src/os/pfsreadwritefile.o    \
    $(BUILD_DIR)/lib/src/os/piacs.o    \
    $(BUILD_DIR)/lib/src/os/si.o    \
    $(BUILD_DIR)/lib/src/os/siacs.o    \
    $(BUILD_DIR)/lib/src/os/sptask.o    \
    $(BUILD_DIR)/lib/src/os/thread.o    \
    $(BUILD_DIR)/lib/src/os/vi.o    \
    $(BUILD_DIR)/lib/src/os/vitbl.o    \
    $(BUILD_DIR)/lib/src/os/__osAiDeviceBusy.o    \
    $(BUILD_DIR)/lib/src/os/__osResetGlobalIntMask.o    \
    $(BUILD_DIR)/lib/src/os/__osSiRawReadIo.o    \
    $(BUILD_DIR)/lib/src/os/__osSiRawStartDma.o    \
    $(BUILD_DIR)/lib/src/os/__osSiRawWriteIo.o    \
    $(BUILD_DIR)/lib/src/os/__osSpDeviceBusy.o    \
    $(BUILD_DIR)/lib/src/os/__osSpRawStartDma.o    \
    $(BUILD_DIR)/lib/src/os/__osSpSetPc.o    \
    $(BUILD_DIR)/lib/src/os/__osViSwapContext.o    \
