.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
leaf wcopy
        move    $2,$0
$LVL1 = .
$L2:
        subu    $3,$6,$2
$LVL2 = .
        bgtz    $3,$L3
        addu    $3,$4,$2

        jr      $31
        nop

$L3:
$LVL3 = .
        lw      $7,0($3)
        addu    $3,$5,$2
        sw      $7,0($3)
$LVL4 = .
        b       $L2
        addiu   $2,$2,4
.end wcopy
