.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

leaf stack_pointer
jr         $ra
or         $v0, $sp, $zero
.end stack_pointer

.global get_clockspeed
.balign 32
get_clockspeed:
    mfc0 $v1, $9
    nop
    mfc0 $v0, $9
    nop
    subu $v0, $v0, $v1
    jr $ra
    srl $v0, $v0, 1
	
.global get_cachemiss
.balign 32
get_cachemiss:
	nop
	nop
    mfc0 $v1, $9
    nop
    mfc0 $v0, $9
    nop
    subu $v0, $v0, $v1
    jr $ra
    srl $v0, $v0, 1

.global reboot_disable_interrupts
.balign 32
reboot_disable_interrupts:
    mfc0 $t0, $12      # $t0 = status register flags
    andi $t0, $t0, 0xFFFE  # Disable interrupts flags
    jr $ra 
    mtc0 $t0, $12      # Write new status flags

.global emux_detect
.balign 32
emux_detect:
or $v0, $0, $0
jr $ra
tne $v0, $v0, 0x0